// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwc06CK3GTKXGJs6QrW4GFMWDySWNyFs',
    appId: '1:955387147947:web:68b67857be13459a50e9ee',
    messagingSenderId: '955387147947',
    projectId: 'examenjovii',
    authDomain: 'examenjovii.firebaseapp.com',
    storageBucket: 'examenjovii.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpnhmIATkMZBcJcD9J5UcEP0PNb5L6Ks',
    appId: '1:955387147947:android:17bfcb1dccc58aa250e9ee',
    messagingSenderId: '955387147947',
    projectId: 'examenjovii',
    storageBucket: 'examenjovii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YINmEzABDoeIyg1h7x2FVl_gxTaYUzE',
    appId: '1:955387147947:ios:06ec7a02efc76aab50e9ee',
    messagingSenderId: '955387147947',
    projectId: 'examenjovii',
    storageBucket: 'examenjovii.firebasestorage.app',
    iosBundleId: 'com.example.exajovii',
  );
}
